#include "common_utils.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Define the units to be used with the software delay function */
const bsp_delay_units_t bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;

bsp_io_level_t pin_level = BSP_IO_LEVEL_LOW;

uint8_t g_freq = 0;

void blink_led(uint8_t rec, bsp_io_port_pin_t pin);
uint8_t g_can_read_data();

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
    while(true)
    {
        R_BSP_PinAccessEnable();
        g_freq = g_can_read_data();
        if (g_freq > 0)
        {
            blink_led(g_freq, (bsp_io_port_pin_t) BSP_IO_PORT_04_PIN_15);
        }
        else
        {
            R_BSP_PinWrite((bsp_io_port_pin_t) BSP_IO_PORT_04_PIN_15, BSP_IO_LEVEL_LOW);
        }

        /* Protect PFS registers */
        R_BSP_PinAccessDisable();
    }
}

/*******************************************************************************************************************//**
 * @} (end defgroup CAN_EP)
 **********************************************************************************************************************/
void blink_led(uint8_t rec, bsp_io_port_pin_t pin)
{
    /* Set the blink frequency (must be <= bsp_delay_units */
    uint32_t freq_in_hz = rec;

    /* Calculate the delay in terms of bsp_delay_units */
    uint32_t delay = bsp_delay_units / freq_in_hz;

    R_BSP_PinWrite((bsp_io_port_pin_t) pin, pin_level=(pin_level==BSP_IO_LEVEL_LOW)?pin_level = BSP_IO_LEVEL_HIGH:BSP_IO_LEVEL_LOW);
    R_BSP_SoftwareDelay(delay, bsp_delay_units);
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
